### ISSUE TITLE
Update i3-gaps to 4.18.3

### ISSUE THREAD

**Issue by ChristofferKarlsson** [Fuhrmann/copr-specs#1]
A new version of i3-gaps is now available: https://github.com/Airblader/i3/releases/tag/4.18.3

**Comment by Fuhrmann** [comment]
Updated, thanks @ChristofferKarlsson!

**Comment by Fuhrmann** [comment]
Build results: https://copr.fedorainfracloud.org/coprs/fuhrmann/i3-gaps/build/1716365/
